export const appointments = [
  {
    id: 1,
    userId: 1,
    name: "Preeti Sharma",
    age: 28,
    gender: "Female",
    email: "john@gmail.com",
    phone: 9205908623,
    profileUrl: "assets/images/avatar1.png",
    appointmentStartTime: "2022-06-10T13:30:00Z",
    appointmentEndTime: "2022-06-10T13:45:00Z",
    symptoms: "Swelling and stiffness in Knee",
    appointmentStatus: "UPCOMING",
  },
  {
    id: 2,
    userId: 2,
    name: "Harish Kumar",
    age: 25,
    gender: "Male",
    email: "donna@gmail.com",
    phone: 9205908623,
    profileUrl: "assets/images/avatar2.png",
    appointmentStartTime: "2022-06-10T13:45:00Z",
    appointmentEndTime: "2022-06-10T14:00:00Z",
    symptoms: "Weakness, Pain in knee",
    appointmentStatus: "UPCOMING",
  },
  {
    id: 3,
    userId: 3,
    name: "Aniket Mishra",
    age: 52,
    gender: "Male",
    email: "ella@gmail.com",
    phone: 9205908623,
    profileUrl: "assets/images/avatar3.png",
    appointmentStartTime: "2022-06-10T14:00:00Z",
    appointmentEndTime: "2022-06-10T14:15:00Z",
    symptoms: "Popping noise in knee on sitting",
    appointmentStatus: "UPCOMING",
  },
  {
    id: 4,
    userId: 4,
    name: "Amaira George",
    age: 32,
    gender: "Female",
    email: "amaira@gmail.com",
    phone: 9205908623,
    profileUrl: "assets/images/avatar4.png",
    appointmentStartTime: "2022-06-10T14:15:00Z",
    appointmentEndTime: "2022-06-10T14:30:00Z",
    symptoms: "Not able to fully straighten the knee",
    appointmentStatus: "UPCOMING",
  },
  {
    id: 5,
    userId: 5,
    name: "Amrita K",
    age: 33,
    gender: "Female",
    email: "amrita@gmail.com",
    phone: 9205908623,
    profileUrl: "assets/images/avatar4.png",
    appointmentStartTime: "2022-05-30T14:15:00Z",
    appointmentEndTime: "2022-05-30T14:30:00Z",
    symptoms: "Not able to fully straighten the knee",
    appointmentStatus: "COMPLETED",
    treatment: {
      type: "WRITTEN",
      diagnosis: "Muscle pull",
      prescription: [
        "Gabapin - After dinner",
        "Omnigel - Apply 3 times a day",
        "Shelcal - After lunch",
        "Follow for 15 days",
      ],
    },
  },
  {
    id: 6,
    userId: 2,
    name: "Harish Kumar",
    age: 25,
    gender: "Male",
    email: "donna@gmail.com",
    phone: 9205908623,
    profileUrl: "assets/images/avatar2.png",
    appointmentStartTime: "2022-06-03T13:45:00Z",
    appointmentEndTime: "2022-06-03T14:00:00Z",
    symptoms: "Weakness, Pain in knee",
    appointmentStatus: "COMPLETED",
    treatment: {
      type: "WRITTEN",
      diagnosis: "Muscle pull",
      prescription: [
        "Gabapin - After dinner",
        "Omnigel - Apply 3 times a day",
        "Shelcal - After lunch",
        "Follow for 15 days",
      ],
    },
  },
  {
    id: 7,
    userId: 3,
    name: "Aniket Mishra",
    age: 52,
    gender: "Male",
    email: "ella@gmail.com",
    phone: 9205908623,
    profileUrl: "assets/images/avatar3.png",
    appointmentStartTime: "2022-06-02T14:00:00Z",
    appointmentEndTime: "2022-06-02T14:15:00Z",
    symptoms: "Popping noise in knee on sitting",
    appointmentStatus: "COMPLETED",
    treatment: {
      type: "SNAPSHOT",
      imageUrl: "assets/images/prescription.jpg",
    },
  },
  // {
  //   id: 8,
  //   userId: 6,
  //   name: "Ankush Kumar",
  //   age: 58,
  //   gender: "Male",
  //   email: "ankush@gmail.com",
  //   phone: 9205908623,
  //   profileUrl: "assets/images/avatar4.png",
  //   appointmentStartTime: "2022-05-30T14:45:00Z",
  //   appointmentEndTime: "2022-05-30T15:00:00Z",
  //   symptoms: "Weakness, Pain in knee",
  //   appointmentStatus: "COMPLETED",
  //   treatment: {
  //     type: "SNAPSHOT",
  //     imageUrl: "assets/images/prescription.jpg",
  //   },
  // },
];
